# Generated by Django 4.2 on 2025-02-07 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                error_messages={
                    "unique": "A user with that phone number already exists."
                },
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^09[0-9]\\d{8}$", "Enter a valid phone number", "invalid"
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
