# Generated by Django 4.2 on 2025-02-07 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                error_messages={
                    "unique": "A user with that phone number already exists."
                },
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^989[0-9]\\d{9}$", "Enter a valid phone number", "invalid"
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
